export const allProducts = [
  {
    id: 1,
    name: "Silk Banarasi Saree",
    description: "Traditional handwoven silk with golden zari work",
    price: 12999,
    originalPrice: 15999,
    rating: 4.8,
    reviewCount: 124,
    isNew: true,
    category: "Silk",
    image: "/products/banarasi.png",
  },
  {
    id: 2,
    name: "Chanderi Cotton Saree",
    description:
      "Lightweight cotton with delicate floral motifs. Perfect for daily wear and formal occasions.",
    price: 7999,
    originalPrice: 9999,
    rating: 4.5,
    reviewCount: 89,
    isNew: false,
    category: "Cotton",
    image: "/products/cotton.png",
  },
  {
    id: 3,
    name: "Kanjivaram Silk Saree",
    description: "Rich silk with temple border and intricate designs",
    price: 18999,
    originalPrice: 22999,
    rating: 4.9,
    reviewCount: 156,
    isNew: true,
    category: "Silk",
    image: "/products/kanjivaram.png",
  },
  {
    id: 4,
    name: "Bandhani Printed Saree",
    description: "Traditional tie-dye art with vibrant colors",
    price: 6599,
    originalPrice: 8499,
    rating: 4.3,
    reviewCount: 67,
    isNew: false,
    category: "Cotton",
    image: "/products/bandhani.png",
  },
  {
    id: 5,
    name: "Organza Embroidered Saree",
    description: "Modern sheer fabric with sequin embroidery",
    price: 10999,
    originalPrice: 13999,
    rating: 4.6,
    reviewCount: 92,
    isNew: true,
    category: "Organza",
    image: "/products/organza.png",
  },
  {
    id: 6,
    name: "Tussar Silk Saree",
    description: "Wild silk with natural texture and earthy tones",
    price: 9499,
    originalPrice: 11999,
    rating: 4.4,
    reviewCount: 78,
    isNew: false,
    category: "Silk",
    image: "/products/tussar.png",
  },
  {
    id: 7,
    name: "Net Embellished Saree",
    description: "Contemporary net fabric with stone and bead work",
    price: 13999,
    originalPrice: 17999,
    rating: 4.7,
    reviewCount: 103,
    isNew: true,
    category: "Net",
    image: "/products/net.png",
  },
  {
    id: 8,
    name: "Georgette Printed Saree",
    description:
      "Flowy georgette with contemporary digital prints, perfect for parties",
    price: 6999,
    originalPrice: 8999,
    rating: 4.6,
    reviewCount: 142,
    isNew: true,
    category: "Georgette",
    image: "/products/georgette.png",
  },
  {
    id: 9,
    name: "Patola Silk Saree",
    description: "Double ikat woven silk from Gujarat with geometric patterns",
    price: 24999,
    originalPrice: 29999,
    rating: 4.9,
    reviewCount: 87,
    isNew: false,
    category: "Silk",
    image: "/products/patola.png",
  },
  {
    id: 10,
    name: "Linen Fusion Saree",
    description:
      "Eco-friendly linen blend with minimalist embroidery, office wear suitable",
    price: 5599,
    originalPrice: 7499,
    rating: 4.4,
    reviewCount: 65,
    isNew: true,
    category: "Linen",
    image: "/products/linen.png",
  },
  {
    id: 11,
    name: "Kashmiri Jamawar Saree",
    description:
      "Exquisite Kashmiri craftsmanship with intricate paisley motifs",
    price: 18999,
    originalPrice: 23999,
    rating: 4.8,
    reviewCount: 118,
    isNew: false,
    category: "Jamawar",
    image: "/products/jamawar.png",
  },
  {
    id: 12,
    name: "Chiffon Embroidered Saree",
    description:
      "Sheer chiffon with delicate thread work, ideal for evening events",
    price: 8999,
    originalPrice: 11999,
    rating: 4.5,
    reviewCount: 91,
    isNew: true,
    category: "Chiffon",
    image: "/products/chiffon.png",
  },
  {
    id: 13,
    name: "Paithani Silk Saree",
    description: "Maharashtrian heritage silk with peacock and flower motifs",
    price: 21999,
    originalPrice: 27999,
    rating: 4.9,
    reviewCount: 134,
    isNew: false,
    category: "Silk",
    image: "/products/paithani.png",
  },
  {
    id: 14,
    name: "Crepe Designer Saree",
    description: "Modern crepe with asymmetric prints and contemporary styling",
    price: 7499,
    originalPrice: 9999,
    rating: 4.3,
    reviewCount: 77,
    isNew: true,
    category: "Crepe",
    image: "/products/crepe.png",
  },
  {
    id: 15,
    name: "Mysore Silk Saree",
    description: "Pure Karnataka silk with traditional checks and zari borders",
    price: 16999,
    originalPrice: 20999,
    rating: 4.7,
    reviewCount: 156,
    isNew: false,
    category: "Silk",
    image: "/products/mysore.png",
  },
  {
    id: 16,
    name: "Velvet Embellished Saree",
    description: "Luxury velvet with intricate embroidery and crystal work",
    price: 15999,
    originalPrice: 19999,
    rating: 4.8,
    reviewCount: 103,
    isNew: true,
    category: "Velvet",
    image: "/products/velvet.png",
  },
  {
    id: 17,
    name: "Bhagalpuri Silk Saree",
    description: "Tussar silk from Bhagalpur with natural dye patterns",
    price: 11999,
    originalPrice: 14999,
    rating: 4.6,
    reviewCount: 89,
    isNew: false,
    category: "Silk",
    image: "/products/bhagalpuri.png",
  },
  {
    id: 18,
    name: "Pochampally Ikat Saree",
    description:
      "Traditional ikat weave from Telangana with geometric patterns in earthy colors",
    price: 8499,
    originalPrice: 10999,
    rating: 4.5,
    reviewCount: 73,
    isNew: false,
    category: "Ikat",
    image: "/products/pochampally.png",
  },
  {
    id: 19,
    name: "Kalamkari Printed Saree",
    description:
      "Hand-painted cotton with mythological scenes and floral motifs using natural dyes",
    price: 9999,
    originalPrice: 12999,
    rating: 4.7,
    reviewCount: 98,
    isNew: true,
    category: "Handpainted",
    image: "/products/kalamkari.png",
  },
  {
    id: 20,
    name: "Baluchari Silk Saree",
    description:
      "West Bengal silk with intricate narrative borders depicting mythological stories",
    price: 17999,
    originalPrice: 22999,
    rating: 4.8,
    reviewCount: 112,
    isNew: false,
    category: "Silk",
    image: "/products/baluchari.png",
  },
];
